language: node_js
os: linux
node_js:
  - "11"

branches:
  only:
    - master

notifications:
  email: false

install:
  - npm ci
  - npm install -g gatsby

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master