version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8081"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=production
      - GATSBY_TELEMETRY_DISABLED=1

